version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: meu-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

  pg-admin:
    image: dpage/pgadmin4:6
    container_name: meu-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/challenge
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SECURITY_JWT_SECRET=W1EzKKHt9bOEQEROqvnBFPV0rplU8X45
      - SECURITY_JWT_EXPIRATION=3600000
    ports:
      - "8080:8080"
    restart: always

volumes:
  data:
